server:
  port: 8085

feign:
  sentinel:
    enabled: true
  okhttp:
    enabled: true

spring:
  rabbitmq:
    listener:
      simple:
        acknowledge-mode: auto
        retry:
          enabled: true
          initial-interval: 1000ms # 初识的失败等待时长为1秒
          multiplier: 1 # 失败的等待时长倍数，下次等待时长 = multiplier * last-interval
          max-attempts: 3 # 最大重试次数
          stateless: true # true无状态；false有状

    connection-timeout: 1s
    template:
      retry:
        enabled: true
        initial-interval: 1000ms
        multiplier: 1
        max-attempts: 3

    #这个用来设置生产者确认的消息
    publisher-confirm-type: correlated
    #这个用来设置发送消息的返回值
    publisher-returns: true

  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090
      http-method-specify: true

hm:
  db:
    host: 192.168.200.131
    database: hm-trade
    port: 3306
    un: root
    pw: 123
  swagger:
    title: "黑马商城交易服务接口文档"
    package: com.hmall.trade.controller
