server:
  port: 8082

feign:
  okhttp:
    enabled: true

hm:
  db:
    host: 192.168.200.131
    database: hm-cart
    port: 3306
    un: root
    pw: 123
  swagger:
      title: "黑马商城购物车服务接口文档"
      package: com.hmall.cart.controller
