server:
  port: 8082

#openfeign开启sentinel，也就是可以将远程调用的接口显示出来
feign:
  sentinel:
    enabled: true
  okhttp:
    enabled: true

#这里是这个服务开启sentinel
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090
      http-method-specify: true

hm:
  db:
    host: 192.168.200.131
    database: hm-cart
    port: 3306
    un: root
    pw: 123
  swagger:
      title: "黑马商城购物车服务接口文档"
      package: com.hmall.cart.controller
