server:
  port: 8086

spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090
      http-method-specify: true

hm:
  db:
    host: 192.168.200.131
    database: hm-pay
    port: 3306
    un: root
    pw: 123
  swagger:
    title: "黑马商城支付服务接口文档"
    package: com.hmall.pay.controller
