server:
  port: 8086

spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090
      http-method-specify: true
  rabbitmq:
    connection-timeout: 1s
    template:
      retry:
        enabled: true
        initial-interval: 1000ms
        multiplier: 1
        max-attempts: 3

    #这个用来设置生产者确认的消息
    publisher-confirm-type: correlated
    #这个用来设置发送消息的返回值
    publisher-returns: true

hm:
  db:
    host: 192.168.200.131
    database: hm-pay
    port: 3306
    un: root
    pw: 123
  swagger:
    title: "黑马商城支付服务接口文档"
    package: com.hmall.pay.controller
