server:
  port: 8082

#openfeign开启sentinel，也就是可以将远程调用的接口显示出来
feign:
  sentinel:
    enabled: true
  okhttp:
    enabled: true

#这里是这个服务开启sentinel
spring:
  rabbitmq:
    listener:
      simple:
        acknowledge-mode: auto
        retry:
            enabled: true # 开启消费者失败重试
            initial-interval: 1000ms # 初识的失败等待时长为1秒
            multiplier: 1 # 失败的等待时长倍数，下次等待时长 = multiplier * last-interval
            max-attempts: 3 # 最大重试次数
            stateless: true # true无状态；false有状


  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090
      http-method-specify: true

hm:
  db:
    host: 192.168.200.131
    database: hm-cart
    port: 3306
    un: root
    pw: 123
  swagger:
      title: "黑马商城购物车服务接口文档"
      package: com.hmall.cart.controller
