server:
  port: 8081

feign:
  sentinel:
    enabled: true
  okhttp:
    enabled: true

spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090
      http-method-specify: true

hm:
  db:
    host: 192.168.200.131
    database: hm-item
    port: 3306
    un: root
    pw: 123
  swagger:
    title: "黑马商城商品服务接口文档"
    package: com.hmall.item.controller
